### ISSUE TITLE
有windows和mac桌面版开源的吗？

### ISSUE THREAD

**Issue by stoneWeb** [jianliaoim/talk-os#47]
还是自己直接用electron把web套个壳？
有什么开发文档吗？描述架构和目录结构的？

**Comment by fushutech** [comment]
没有




    
    
        
            
                
                    
                        
                    
                    
                        
                            it
                            
                            
                                
                                    邮箱：it@fushutech.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年10月19日 11:19，Winter 写道： 还是自己直接用electron把web套个壳？
有什么开发文档吗？描述架构和目录结构的？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jianliaoim/talk-os","title":"jianliaoim/talk-os","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jianliaoim/talk-os"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"有windows和mac桌面版开源的吗？ (#47)"}],"action":{"name":"View Issue","url":"https://github.com/jianliaoim/talk-os/issues/47"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jianliaoim/talk-os/issues/47",
"url": "https://github.com/jianliaoim/talk-os/issues/47",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "有windows和mac桌面版开源的吗？ (#47)",
"sections": [
{
"text": "",
"activityTitle": "**Winter**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@stoneWeb",
"facts": [
{
"name": "Repository: ",
"value": "jianliaoim/talk-os"
},
{
"name": "Issue #: ",
"value": 47
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jianliaoim/talk-os\",\n\"issueId\": 47,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jianliaoim/talk-os\",\n\"issueId\": 47\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jianliaoim/talk-os/issues/47"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 398354276\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Boshen** [comment]
都没有。 好几年前的项目了， 只能靠自己摸索了。
